module.exports = {
    BASE_URL: 'https://www.alphavantage.co/query?',
    
    API_KEY: 'ABFF0IIAH5WOBKAU',

    // routes
    ROUTE_INTRADAY: 'TIME_SERIES_INTRADAY',
    ROUTE_INTRADAY_EXTENDED: 'TIME_SERIES_INTRADAY_EXTENDED',
    ROUTE_DAILY: 'TIME_SERIES_DAILY',
    ROUTE_DAILY_ADJUSTED: 'TIME_SERIES_DAILY_ADJUSTED',
    ROUTE_WEEKLY: 'TIME_SERIES_WEEKLY',
};